PARENT=index
NAME=Rólunk
NAVIGATION=yes
CONTENT="
<div class='"'container'"'>
	<div class='"'about-text'"'>
		<h3>Budapest-Budavár Rotaract Club</h3>
		<p>A Budapest-Budavár Rotaract Club 1996-ban, az egyik legelső budapesti Rotaract klubként alakult. Mivel a Rotaractot 18 és 30 év közötti fiatalok alkotják, tagságunk már többször megújult, de mindig összetartó baráti társaságként szerveztük és szervezzük továbbra is projectjeinket.</p>
		<p>Gyűléseinknek célja az, hogy lehetőséget biztosítsunk clubtagjaink számára az ismereteik és szakértelmük bővítésében, valamint segítsük őket személyes fejlődésükben. Közös célunk, hogy a tagok érzékenyen reagáljanak az őket körülvevő közösség kulturális és szociális szükségleteire, valamint elősegítsék a világ népei közötti jobb kapcsolat kialakítását a barátság és segítségnyújtás eszközeivel.</p>
		<p>Természetesen a jó hangulat alapja a barátság, amely minden Rotary és Rotaract Club sajátossága. Ez a tény a Budavárról is maradéktalanul elmondható, amelyet folyamatosan szervezett csapatépítésekkel és projectekkel szilárdítunk meg a hozzánk újonnan csatlakozók esetében.</p>
		<p>Amennyiben szeretnél hozzánk tartozni és a Budapest-Budavár lobogója alatt valami jót cselekedni, mindezt ráadásul egy jó hangulatú, baráti közösség részeként, írj nekünk, vagy látogass el egy gyűlésünkre.</p>
		<h3>Történelem</h3>
		<p>A Rotaract Club Budapest – Budavár megalakulásához vezető események 1995 őszén indultak, amikor az RC Budapest – Budavár ösztönzésére az akkoriban még csak lazán összejárogató néhány klubtag elhatározta, hogy a klubot hivatalosan is megalakítják. Az elhatározást tettek követték, így kapta meg a klub a 1996.november 30.-án a charterét, amivel hazánkban a negyedik klubként csatlakozott a magyarországi Rotaracthoz. Charterükön több, mint 100 külföldi fiatalt láttak vendégül Budapesten, természetesen a magyar vendégek mellett. A klub szervezte meg az első hivatlaos találkozót, District Konferenciát 1995 őszén, 1996 októberében pedig a negyediket. Már megalakulásukat megelőzően is, de azóta még inkább igyekeznek megfelelni rotaractos kötelezettségeiknek és akcióikkal, projectjeikkel szolgálni a körülöttük élő emberek érdekeit, segíteni az arra rászorolúkat. A klub alapító elnöke Pottyondy Kinga volt.</p>

		<h3>A klub működése, fontos események, projectek</h3>
		<p>A klubtagok a gyerekeket, fiatalokat érzik magukhoz legközelebb állónak, így figyelmüket kezdettől fogva a rászoruló gyerekek támogatására fordítják. Támogatják a Venetiáner utcai Kisegítő Általános Iskolát, a Bólyai utcai Gyermekotthont. Nyelvtanulási programjaik és egyéb akcióik is vannak, amelyekkel a gyerekek helyzetén igyekeznek javítani. Ezek a gyerekek nagyon sok mindenben szenvednek hiányt, de legjobban a szeretetre, emberi törődésre vágynak, amit a budavári rotaractosok probálnak megadni nekik. A Rotaract klub 20 éves fennállása alatt számos önkéntest megmozgató rendezvényen vett részt, amelyekrészben hosszabb távú együttműködés keretében valósultak meg, részben ismétlődő jellegűek, részben egyszeri alkalmak voltak. </p>

		<p>Éves rendszerességgel jelennek meg a Vörösmarty téri adventi vásáron, ahol adományokat gyűjtenek. Óvodások, óvónők kézimunkáit ajánlják fel a támogatóknak. A Budapest – Duna Rotaract Club és az Árkád Bevásárlóközpont közreműködésével például 2004 decemberében három hétvégén keresztül gyűjtöttek ajándékokat, régi játékokat és könyveket az Éltes MátyásGyermekotthon hátrányos helyzetű lakói számára. Mivel a Rotary anyaszervezetük kiemelten támogatja a „Jobb velünk a világ” jótékonysági rendezvényét, ezért tevékenyen részt vállalnak ebben a programban. Az eseményre húsz sérült gyereket vittek el a saját költségükön.</p>

		<p>A „cipős doboz” akcióban évek óta részt vesznek. Más klubok programjaiba is gyakran bekapcsolódnak, például aktívan támogatták a Budapest – Margitsziget Gyerkőckarácsonyát, amely tavaly már a budapesti klubok együttes szervezésével valósult meg a Papp László Sportarénban, ahol 80 hátrányos helyzetű gyermeket láttak vendégül, szerveztek nekik programokat és megajándékozták őket Havasi koncertjegyekkel.
		„Egy ember, két keréken, három Amerikán át” project 1997 tavaszán Mészáros János székesfehérvári ultratriatlonista jótékonysági kerékpáros útját támogatták. Mészáros János és csapata arra vállalkoztak, hogy felhívja a figyelmet a nemzetközi Speciális Olimpia résztvevőire és céljaira, valamint a Sclerosis  Multiplex betegségben szenvedő emberekre. Az akcióból befolyt pénzöszeget egy új szociális otthon felépítésére ajánlották fel a betegségben szenvedők számára. A klub a támogató klubjával, a Budapest – Budavár Rotary Clubbal közösen értesítette a magyar kerékpárosok útvonalába eső amerikai Rotary és Rotaract klubokat, hogy Mészáros Jánosnak és csapatának szállást biztosítsanak, akik így számos helyen élvezhették a klubok vendégszeretetét. </p>

		<h4>Boráros téri takarító akció</h4>
		<p>A klubtagok 1997 novemberében Budapest egy kis pontjának megszépítését célozták meg. Az FKF Rt.-vel együttműködve arra vállalkoztak, hogy megtisztítják a főváros egyik legforgalmasabb közlekedési csomópontját, a Boráros tér kiterjedt aluljáró-hálózatát.</p>
		<h4>Shadowing</h4>
		<p>A pályaválasztás előtt álló gimnazistáknak először 2005-ben tette lehetővé a klub, hogy fél-fél napra valódi munkahelyeken nyerjenek betekintést az általuk választott szakmákba, és így egy átfogóbb képet alkothassanak a szakterületről, illetve az ott folyó munkáról. A programot három éven keresztül szervezték, ami olyan népszerűvé vált az iskolákban, hogy a szülők folytatták a kezdeményezést.</p>
		<h4>Koszorú utcai óvoda támogatása</h4>
		<p>A klub 2009-től vállalta a VIII. kerületi Koszorú utcai óvoda támogatását, így azóta évente több alkalommal ellátogatnak a klubtagok különböző jeles alkalmakkor, amelyet még sok-sok éven keresztül tervezik megszervezni és ezzel örömet okozni az ovisoknak, valamint némi képpen a tanítóknak is.</p>
		<h4>Jótékonysági filmvetítés</h4>
		<p>Fundraising projektnek indult a Koszorú utcai ovimikulás költségeinek támogatására, de önállóan is megállja a helyét az olyan filmek vetítése, amelyek olyan tartalommal, mondani valóval bírnak, amik nem csak szórakoztatnak, de tanítanak is, elgondolkodtatnak az életről és a benne elfoglalt helyünkról. A klub a Budapest Rooftop Cinema segítségével szervezte meg 2015-ben először, remélhetőleg nem utoljára egy ilyen jellegű film vetítését.</p>
	</div>
</div>"
